version: '3'
services:
  web:
    container_name: PLAYLIST_NGINX
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro

  php:
    container_name: PLAYLIST_PHP
    build: ./docker/php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./public:/var/www/public:ro
      - ./src:/var/www/src:ro
      - ./vendor:/var/www/vendor:ro
      - ./config:/var/www/config:ro

  db:
    container_name: PLAYLIST_DB
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: playlist_demo
      MYSQL_USER: user
      MYSQL_PASSWORD: userpwd
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d

  adminer:
    container_name: PLAYLIST_ADMINER
    image: adminer
    restart: always
    ports:
      - 8000:8080
