version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf

  php:
    build: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./config:/var/www/config

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: playlist_demo
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
